services:
  db:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis
    restart: always
    ports:
      - ${CACHE_PORT}:${CACHE_PORT}
