const AUTHENTICATION_TYPE_KEY = Symbol('AUTH_TYPE');
const JWT_CONFIG = Symbol('jwt');
const REQUEST_USER_KEY = Symbol('user');
const PG_UNIQUE_VIOLATION_ERROR_CODE = '23505';

export {
  AUTHENTICATION_TYPE_KEY,
  JWT_CONFIG,
  PG_UNIQUE_VIOLATION_ERROR_CODE,
  REQUEST_USER_KEY,
};
